name: DataDrivenTesting.podspec validation

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  linters:
    name: Run linters
    runs-on: macos-13
    steps:
      - uses: actions/checkout@v3
      - name: Cache bundler gems
        uses: actions/cache@v3
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-
      - name: Bundler
        run: |
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3
      - run: bundle exec pod spec lint
